In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("/home/jiaruil5/personality/llm_personality/psychgenerator_opensource/data/big5_training_data.csv", header = 0, index_col = 0)
df

,message,ope_z,con_z,ext_z,agr_z,neu_z
message_id,,,,,,
tweet_143508,""";;tengo mi penchi fierron up in the air & its...",-0.300409,0.459249,0.294330,0.452765,-0.894041
tweet_425070,perhaps he loved everyone but me. nbut that ma...,0.896169,0.493197,-0.414594,0.337368,0.393312
tweet_502775,"if you have 3 coffee cups in your car, you hav...",0.213276,0.176036,0.328285,0.274713,-0.211072
tweet_600640,i'm too sleepy to start work in an hour,-0.711772,1.284832,-1.013234,0.611918,0.545335
blog_79108,i worked for a recruiter a little bit after i ...,1.837614,0.042504,-0.460709,0.061335,1.808086
...,...,...,...,...,...,...
blog_46845,hey what do u think of 'unwell' by matchbox 20...,0.076771,-0.211666,0.577826,0.861935,-0.708217
tweet_611609,my life is dedicated to school right now ready...,-1.700926,1.092124,1.216876,1.034062,-0.978274
blog_107867,bush and cheney continue to assert that there ...,2.278704,0.275908,0.107220,-1.885664,-0.970312
blog_178310,sometimes my in-laws do things that are totall...,1.589152,-0.109238,1.157105,0.405037,-0.363393
blog_546171,i don't believe this shit... jules actually bo...,-1.079073,0.279342,0.110034,-0.759008,-0.277343

In [2]:
df = df.sample(frac=1, random_state=42)

In [3]:
# convert to continuous labels from 0 to 1
from scipy.stats import norm
for i in ['ope_z', 'con_z', 'ext_z', 'agr_z', 'neu_z']:
    df[f'{i}_label'] = norm.cdf(df[i])
df

,message,ope_z,con_z,ext_z,agr_z,neu_z,ope_z_label,con_z_label,ext_z_label,agr_z_label,neu_z_label
message_id,,,,,,,,,,,
tweet_79485,afternoon beer and football. love bank hol wee...,-0.853325,1.214615,0.956297,0.609369,-1.163561,0.196740,0.887744,0.830539,0.728860,0.122301
blog_285431,i'm not much of a curser.i have a pretty exten...,0.788133,-1.148048,-0.697936,-0.121973,0.244505,0.784691,0.125474,0.242609,0.451460,0.596580
tweet_592581,spent the entire day with my momma. and it was...,2.261982,1.040296,0.777304,0.772384,0.043052,0.988151,0.850899,0.781510,0.780057,0.517170
blog_243831,"i layed in bed last night, restlessly tossing ...",0.395613,-1.083703,-0.547173,0.079361,2.106501,0.653805,0.139248,0.292130,0.531627,0.982420
blog_232829,in the a.m.this has to be the sixteenth effort...,0.327434,-0.160491,0.068643,0.426739,0.546140,0.628330,0.436247,0.527363,0.665215,0.707515
...,...,...,...,...,...,...,...,...,...,...,...
tweet_156286,playing arkham asylum. i am the bat.,-0.362510,-0.284443,-0.495203,-0.114894,-0.515912,0.358485,0.388035,0.310229,0.454264,0.302958
tweet_176785,the last 15 seconds i mean 10 minutes of this ...,-0.445762,0.703433,-0.322847,-0.083888,0.540805,0.327885,0.759107,0.373406,0.466573,0.705679
blog_372010,"as you may have noticed, my post titles have b...",-0.026976,-1.064666,-0.541605,-0.251065,-0.584829,0.489239,0.143514,0.294045,0.400882,0.279332
tweet_510126,it was just brought to my attention that some ...,-0.368077,0.366800,-0.118484,0.648479,0.983599,0.356408,0.643116,0.452842,0.741662,0.837344
tweet_349720,lol that's wat it feel like!,0.634327,-1.225564,-0.143024,0.313106,0.475587,0.737066,0.110181,0.443135,0.622900,0.682816

In [4]:
df[['ope_z_label', 'con_z_label', 'ext_z_label', 'agr_z_label', 'neu_z_label']].describe()

        ope_z_label   con_z_label   ext_z_label    agr_z_label   neu_z_label
count  8.463040e+05  8.463040e+05  8.463040e+05   8.463040e+05  8.463040e+05
mean   4.909413e-01  5.074367e-01  4.995523e-01   5.160894e-01  4.817772e-01
std    2.704310e-01  2.712089e-01  2.688126e-01   2.646097e-01  2.603914e-01
min    4.645134e-72  2.342391e-58  2.778528e-61  7.759210e-130  1.152019e-23
25%    2.745852e-01  2.918431e-01  2.879748e-01   3.153016e-01  2.790008e-01
50%    4.721532e-01  5.236158e-01  5.019260e-01   5.445545e-01  4.545539e-01
75%    7.035639e-01  7.237059e-01  7.093967e-01   7.246917e-01  6.717212e-01
max    1.000000e+00  1.000000e+00  1.000000e+00   1.000000e+00  1.000000e+00

In [5]:
filter_df = df.drop(columns=["ope_z", "con_z", "ext_z", "agr_z", "neu_z"])
filter_df

,message,ope_z_label,con_z_label,ext_z_label,agr_z_label,neu_z_label
message_id,,,,,,
tweet_79485,afternoon beer and football. love bank hol wee...,0.196740,0.887744,0.830539,0.728860,0.122301
blog_285431,i'm not much of a curser.i have a pretty exten...,0.784691,0.125474,0.242609,0.451460,0.596580
tweet_592581,spent the entire day with my momma. and it was...,0.988151,0.850899,0.781510,0.780057,0.517170
blog_243831,"i layed in bed last night, restlessly tossing ...",0.653805,0.139248,0.292130,0.531627,0.982420
blog_232829,in the a.m.this has to be the sixteenth effort...,0.628330,0.436247,0.527363,0.665215,0.707515
...,...,...,...,...,...,...
tweet_156286,playing arkham asylum. i am the bat.,0.358485,0.388035,0.310229,0.454264,0.302958
tweet_176785,the last 15 seconds i mean 10 minutes of this ...,0.327885,0.759107,0.373406,0.466573,0.705679
blog_372010,"as you may have noticed, my post titles have b...",0.489239,0.143514,0.294045,0.400882,0.279332
tweet_510126,it was just brought to my attention that some ...,0.356408,0.643116,0.452842,0.741662,0.837344
tweet_349720,lol that's wat it feel like!,0.737066,0.110181,0.443135,0.622900,0.682816

In [6]:
from sklearn.model_selection import train_test_split
train_df, test_df = train_test_split(filter_df, test_size=0.05, random_state=42)

In [7]:
train_df

,message,ope_z_label,con_z_label,ext_z_label,agr_z_label,neu_z_label
message_id,,,,,,
tweet_284066,i can't talk so ima dm you,0.171419,0.568365,0.364455,0.534305,0.351097
tweet_157848,dylan and i are texting the most crude texts t...,0.613441,0.544047,0.869944,0.550056,0.536529
tweet_102699,this weekend we wildin out to jowell y randy ??,0.596559,0.871041,0.950079,0.761066,0.287603
tweet_539796,this is my zen. music blaring in my headphones...,0.945895,0.327691,0.313968,0.708814,0.489626
blog_383291,wala me masabi kung hindi ang skit ng buo kong...,0.231456,0.609753,0.295073,0.658490,0.384902
...,...,...,...,...,...,...
blog_591894,i think the presentation could have used some ...,0.741987,0.660030,0.084769,0.476406,0.445166
blog_469118,i'll think of you and probably laugh,0.728246,0.003190,0.325534,0.999080,0.937089
blog_385508,"so, i said the other day that i had seen steve...",0.415138,0.830316,0.709938,0.519976,0.550542
blog_222350,just to give our fullest moral support from ma...,0.496754,0.468322,0.640195,0.698710,0.542181
tweet_231175,"""investing in others opens doors. """"a man's gi...",0.478904,0.962611,0.667066,0.738195,0.465037

In [8]:
train_df, val_df = train_test_split(train_df, test_size=0.1, shuffle=False)
train_df

,message,ope_z_label,con_z_label,ext_z_label,agr_z_label,neu_z_label
message_id,,,,,,
tweet_284066,i can't talk so ima dm you,0.171419,0.568365,0.364455,0.534305,0.351097
tweet_157848,dylan and i are texting the most crude texts t...,0.613441,0.544047,0.869944,0.550056,0.536529
tweet_102699,this weekend we wildin out to jowell y randy ??,0.596559,0.871041,0.950079,0.761066,0.287603
tweet_539796,this is my zen. music blaring in my headphones...,0.945895,0.327691,0.313968,0.708814,0.489626
blog_383291,wala me masabi kung hindi ang skit ng buo kong...,0.231456,0.609753,0.295073,0.658490,0.384902
...,...,...,...,...,...,...
tweet_343695,"you.. make.. all things new. yes, <newline> y...",0.470395,0.856899,0.806548,0.901715,0.403901
blog_575940,"this is kind of off topic, but i have to ask.....",0.463068,0.492018,0.653026,0.115115,0.531229
blog_365068,"well hey guys, its monday mornin and its aroun...",0.497448,0.587922,0.987553,0.345747,0.537698
tweet_349282,i'll never let envious people try to tear me o...,0.493329,0.480546,0.554141,0.638933,0.601156
blog_236392,"once again, i have stayed up all night with ch...",0.379540,0.582004,0.788803,0.913379,0.418390

In [10]:
val_df

,message,ope_z_label,con_z_label,ext_z_label,agr_z_label,neu_z_label
message_id,,,,,,
blog_126162,$$$ after we were informed that we wont be ...,0.475234,0.053282,0.086094,0.026188,0.922935
blog_140413,"new flesh last night, the first night of what ...",0.663821,0.550340,0.765085,0.580555,0.237641
tweet_650466,33 days without alcohol: i think my friends ar...,0.317177,0.601739,0.581143,0.485209,0.408250
tweet_318854,yooooo why are ppl following this dude be ur o...,0.210601,0.338706,0.757299,0.106179,0.304725
tweet_269740,uaf heads on the powerplay for the fourth time...,0.424812,0.738609,0.592954,0.547980,0.301427
...,...,...,...,...,...,...
blog_591894,i think the presentation could have used some ...,0.741987,0.660030,0.084769,0.476406,0.445166
blog_469118,i'll think of you and probably laugh,0.728246,0.003190,0.325534,0.999080,0.937089
blog_385508,"so, i said the other day that i had seen steve...",0.415138,0.830316,0.709938,0.519976,0.550542
blog_222350,just to give our fullest moral support from ma...,0.496754,0.468322,0.640195,0.698710,0.542181
tweet_231175,"""investing in others opens doors. """"a man's gi...",0.478904,0.962611,0.667066,0.738195,0.465037

In [12]:
test_df

,message,ope_z_label,con_z_label,ext_z_label,agr_z_label,neu_z_label
message_id,,,,,,
tweet_207056,my phones acting a little slow.. then i rememb...,0.546865,3.448985e-01,0.193607,0.197134,0.707174
blog_176919,well today was the day we got our mid-term mar...,0.337611,6.526791e-01,0.267150,0.744931,0.169102
blog_686715,being sick sucks. merry christmas eve to all.,0.003329,7.407408e-02,0.000015,0.000398,1.000000
blog_270817,"life's too short.... don't know what did it, ...",0.445349,6.171130e-01,0.401443,0.344739,0.549671
tweet_157250,poison girl is stuck in my head urgh,0.887280,1.981526e-11,0.000002,0.009375,1.000000
...,...,...,...,...,...,...
tweet_637400,i need my dick sucked on,0.061459,1.354341e-01,0.349162,0.064509,0.483389
blog_455581,"dear..i am sorry , i shld understand ur feelin...",0.150521,2.275974e-01,0.664807,0.359131,0.873002
blog_117094,i've always been a collector.i've collected st...,0.918159,3.433550e-01,0.467602,0.763303,0.389223
blog_584046,"sonic friday with my mood and the weather, ...",0.135660,3.076567e-01,0.229652,0.241218,0.966518
tweet_413010,"i can't wait to get home, change into sweats, ...",0.117134,5.104848e-01,0.091136,0.682797,0.652600

In [9]:
train_df.to_csv("/data/user_data/wenkail/llm_personality/data/big5_data_classifier_train.csv", index=True)
val_df.to_csv("/data/user_data/wenkail/llm_personality/data/big5_data_classifier_val.csv", index=True)
test_df.to_csv("/data/user_data/wenkail/llm_personality/data/big5_data_classifier_test.csv", index=True)