In [20]:
import pandas as pd
import rich

In [2]:
data = pd.read_csv("big5_training_data_filtered.csv")
data

,message_id,message,ope_z,con_z,ext_z,agr_z,neu_z
0,tweet_143508,""";;tengo mi penchi fierron up in the air & its...",-0.300409,0.459249,0.294330,0.452765,-0.894041
1,tweet_425070,perhaps he loved everyone but me. nbut that ma...,0.896169,0.493197,-0.414594,0.337368,0.393312
2,tweet_502775,"if you have 3 coffee cups in your car, you hav...",0.213276,0.176036,0.328285,0.274713,-0.211072
3,tweet_600640,i'm too sleepy to start work in an hour,-0.711772,1.284832,-1.013234,0.611918,0.545335
4,blog_79108,i worked for a recruiter a little bit after i ...,1.837614,0.042504,-0.460709,0.061335,1.808086
...,...,...,...,...,...,...,...
807525,blog_46845,hey what do u think of 'unwell' by matchbox 20...,0.076771,-0.211666,0.577826,0.861935,-0.708217
807526,tweet_611609,my life is dedicated to school right now ready...,-1.700926,1.092124,1.216876,1.034062,-0.978274
807527,blog_107867,bush and cheney continue to assert that there ...,2.278704,0.275908,0.107220,-1.885664,-0.970312
807528,blog_178310,sometimes my in-laws do things that are totall...,1.589152,-0.109238,1.157105,0.405037,-0.363393
807529,blog_546171,i don't believe this shit... jules actually bo...,-1.079073,0.279342,0.110034,-0.759008,-0.277343

In [34]:
data['message']

0         ";;tengo mi penchi fierron up in the air & its...
1         perhaps he loved everyone but me. nbut that ma...
2         if you have 3 coffee cups in your car, you hav...
3                   i'm too sleepy to start work in an hour
4         i worked for a recruiter a little bit after i ...
                                ...
807525    hey what do u think of 'unwell' by matchbox 20...
807526    my life is dedicated to school right now ready...
807527    bush and cheney continue to assert that there ...
807528    sometimes my in-laws do things that are totall...
807529    i don't believe this shit... jules actually bo...
Name: message, Length: 807530, dtype: object

In [31]:
message_length.describe()

count    807530.000000
mean        149.723764
std         170.956222
min           9.000000
25%          59.000000
50%         125.000000
75%         194.000000
max       60634.000000
Name: message, dtype: float64

In [4]:
bins = [-3, -2, -1, 0, 1, 2, 3]
labels = [1, 2, 3, 4, 5, 6]

# 对每一列进行分级
for col in ['ope_z', 'con_z', 'ext_z', 'agr_z', 'neu_z']:
    data[col + '_level'] = pd.cut(data[col], bins=bins, labels=labels, include_lowest=True)

In [8]:
data.drop(["ope_z", "con_z", "ext_z", "agr_z", "neu_z"], axis=1 )

,message_id,message,ope_z_level,con_z_level,ext_z_level,agr_z_level,neu_z_level
0,tweet_143508,""";;tengo mi penchi fierron up in the air & its...",3,4,4,4,3
1,tweet_425070,perhaps he loved everyone but me. nbut that ma...,4,4,3,4,4
2,tweet_502775,"if you have 3 coffee cups in your car, you hav...",4,4,4,4,3
3,tweet_600640,i'm too sleepy to start work in an hour,3,5,2,4,4
4,blog_79108,i worked for a recruiter a little bit after i ...,5,4,3,4,5
...,...,...,...,...,...,...,...
807525,blog_46845,hey what do u think of 'unwell' by matchbox 20...,4,3,4,4,3
807526,tweet_611609,my life is dedicated to school right now ready...,2,5,5,5,3
807527,blog_107867,bush and cheney continue to assert that there ...,6,4,4,2,3
807528,blog_178310,sometimes my in-laws do things that are totall...,5,3,5,4,3
807529,blog_546171,i don't believe this shit... jules actually bo...,2,4,4,3,3

In [11]:
degree_data = data.drop(["ope_z", "con_z", "ext_z", "agr_z", "neu_z"], axis=1 )
degree_data

,message_id,message,ope_z_level,con_z_level,ext_z_level,agr_z_level,neu_z_level
0,tweet_143508,""";;tengo mi penchi fierron up in the air & its...",3,4,4,4,3
1,tweet_425070,perhaps he loved everyone but me. nbut that ma...,4,4,3,4,4
2,tweet_502775,"if you have 3 coffee cups in your car, you hav...",4,4,4,4,3
3,tweet_600640,i'm too sleepy to start work in an hour,3,5,2,4,4
4,blog_79108,i worked for a recruiter a little bit after i ...,5,4,3,4,5
...,...,...,...,...,...,...,...
807525,blog_46845,hey what do u think of 'unwell' by matchbox 20...,4,3,4,4,3
807526,tweet_611609,my life is dedicated to school right now ready...,2,5,5,5,3
807527,blog_107867,bush and cheney continue to assert that there ...,6,4,4,2,3
807528,blog_178310,sometimes my in-laws do things that are totall...,5,3,5,4,3
807529,blog_546171,i don't believe this shit... jules actually bo...,2,4,4,3,3

In [ ]:
degree_data['ope_z_level'].value_counts()

In [23]:
big_columns = ['ope_z_level', 'con_z_level', 'ext_z_level', 'agr_z_level', 'neu_z_level']
for col in big_columns:
    rich.print(degree_data[col].value_counts())

ope_z_level
3    336491
4    274293
2     87065
5     81247
6     17307
1     11127
Name: count, dtype: int64

con_z_level
4    335285
3    279030
5     87601
2     78485
1     13990
6     13139
Name: count, dtype: int64

ext_z_level
4    313296
3    304592
5     82414
2     79560
6     15319
1     12349
Name: count, dtype: int64

agr_z_level
4    367007
3    261850
5     82287
2     72109
1     17095
6      7182
Name: count, dtype: int64

neu_z_level
3    381683
4    259950
2     77341
5     66737
6     15812
1      6007
Name: count, dtype: int64